### ISSUE TITLE
黑科技：网页由 [你大爷] 提供

### ISSUE THREAD

**Issue by Monine** [Monine/monine.github.io#10]
上周军哥在 [学前班班会 37 期](http://f2e-journey.github.io/xueqianban/#issues/45) 技术类中介绍 “如何自定义微信中的域名提示”，我一向对这种黑科技感兴趣，趁着周末有空，赶紧试玩。

![](https://picabstract-preview-ftn.weiyun.com:8443/ftn_pic_abs_v2/146c95147c8bc6d7b8bff804f483710ba5c7fcb536bd7cbbc8f5270fc6baa60d6ca81dc57bf7cb4ba507eb3b61f5bdb6?pictype=scale&from=30013&version=2.0.0.2&uin=287531381&fname=dark-hand-iphone.jpg&size=1024*1024)

- Q：[你大爷] 是什么鬼？

  Anything you can enter!

![](https://picabstract-preview-ftn.weiyun.com:8443/ftn_pic_abs_v2/be03fe3cb31b0d7a49367307954461ffcddf2df22b178a1a09a08009c75d9ee90f8181721050e115c1f630c46d256670?pictype=scale&from=30013&version=2.0.0.2&uin=287531381&fname=overscroll.png&size=1024*1024)

OK... 恶搞时间结束，咱还是言归正传。众所(前端er)周知，微信浏览器有在交互上有一个特点，当页面上滚到最顶部后继续往上滚会出现当前网页的域名信息，黑底白字。我们的目标，就是要改变黑底的白字内容。如何实现？

**核心在于将滚动事件始终作用于内容滚动层**

#### 具体实现：

1. 伪造黑底白字，咱前端做这种事情简直是秒秒钟搞定。
2. 内容滚动层大小占满整个屏幕，设置内容溢出可滚动，不要设置背景色，不然会遮盖黑底白字，它就是一个可滚动的外框。
3. 内容滚动层内添加页面主体内容包裹层，相当于 `body` 元素，大小也占满整个屏幕，需设置底色。
4. 页面主体内容包裹层内添加页面内容就 OK 啦！

万事俱备，只欠东(J)风(S)，还需要给页面添加一点黑魔法。哈哈... 这里又要祭出我上两篇文章 [梳理 Javascript 各种宽高属性](https://monine.github.io/#!/article/8) [*掘金地址*](https://gold.xitu.io/entry/583a9d4961ff4b007ecbfaff/detail)、[ScrollBar 的归属 - 谁拥有滚动条？](https://monine.github.io/#!/article/9) [*掘金地址*](https://gold.xitu.io/entry/583ab7f0ac502e006c1c6eff/detail)。JS 要做的事情很简单，围绕上述核心思考，结合上两篇文章做参考，然后使用下面的黑魔法，给内容滚动层添加 touchstart 事件，在此状态下：

1. 当页面处于最顶部的时候，内容滚动层向上(滚动条向下)滚动 1px。
2. 当页面处于最底部的时候，内容滚动层向下(滚动条向上)滚动 1px。

这样，滚动事件就始终作用在内容滚动层而不会到达上层 `body` 元素。OK... 介绍到这里，基本的实现就已经完成啦，还有一个小细节就请自行查看 [demo](https://monine.github.io/study/demo/overscroll.html)。

*经 [Binaryify](https://github.com/Binaryify) 提醒，此黑科技目前只能在 iPhone 上有效。* 😂

**Comment by Binaryify** [comment]
并没有效果

**Comment by Monine** [comment]
@Binaryify 
是在手机微信浏览器打开的嘛？

**Comment by Binaryify** [comment]
@Monine 是的,你有在安卓上测试过吗

**Comment by Monine** [comment]
@Binaryify 
刚测试了下，确实没效果 😂
