### ISSUE TITLE
我的 2016

### ISSUE THREAD

**Issue by Monine** [Monine/monine.github.io#12]
2016 年是我第二个本命年，没有其他人说的有多倒霉，反而感觉很幸运。在自己喜爱的行业间步前行，和自己喜欢的人在一起生活，最好的朋友感情依旧，家人平安 ... 还有什么比这些更重要了？
2016 拜拜，我再也不会有比你更年轻的时候，我希望你会觉得我并没有虚度你，感谢你给我的时光。
2017 你好，希望你能带给我幸运，希望我们能彼此珍惜。

![](https://picabstract-preview-ftn.weiyun.com:8443/ftn_pic_abs_v2/a69b25bfc3b0617f3bf2be4b5b121d77ab7ee9ec3117b4d2d4281fd61ed46cf73061bc0b32e6c865642e1c1ec3de07ba?pictype=scale&from=30013&version=2.0.0.2&uin=287531381&fname=clock.jpg&size=1024*1024)

### 工作
在智云做前端已经一年近五个月，当初的小菜鸟现在也可以带新人一起学习啦，希望她能够尽早成长起来。

公司今年变动挺大，因为发展迅速，之前跟微时代一起的办公场所已经容纳不下所有员工，四月份就从好莱城搬到芯城科技园，那时公司应该有一百多号员工。然而互联网行业终于开始冷静，所谓的 “互联网寒冬” 悄然来袭，对我们这种创业型互联网公司来说就是火烧粮仓，在没有持续稳定投资资金进来的情况下，只能自断其尾，淘汰对公司没有贡献的人和项目。公司其他部门不做说明，就研发这边而言，砍掉了本是主力部队的电商项目及相关开发人员，因为项目太烧钱，公司目前无力支持，也有部门开发人员看到公司不景气而自动离职，最后剩下的都是在公司干了最少一年的小伙伴，唯一一个例外就是我正在带着学习的前端妹纸。公司目前也还一直处于生死线边缘，能够活下来没问题，可是能活多久不确定。

今年做的项目挺杂，简单列一下：
1. [70度制作平台](http://my.70c.com/)
  项目现在只维护，不更新，目前的版本是 5.13.0。回顾从加入智云70度团队参与 H5 制作平台项目开发，我都做了哪些事情：
  - 环境 (落物) 特效
  - 重力感应特效
  - 编辑页面预览和设置面板
  - svg 图形及使用 svg 图形裁剪图片 *很强大的功能*
  - 粒子化动效
  - 红包 *招牌功能*
  - 表单的下拉列表
  - 弹幕
  - 地图 *重构*
  - 抽奖 *包括九宫格和大转盘，集成红包。*
  - 商品 *微店铺项目*
  - 淡入翻页和掉落翻页

  大致是以上这些功能，记得当时加入团队做前端开发，完全不懂 AngularJS，JS 的基础也不牢固，突然就上手制作平台这么复杂的项目，看项目内的代码跟看天书没什么区别，很是艰难。当时我还是个只用过 jQuery 和 underscroll 库的少年，对于前端 MVC 的思想完全不懂，也根本不明白什么双向数据绑定、依赖、指令、控制器等等名词。靠着军哥指点，自己每天加班加点努力自学，看书、看视频、看网上各种资料，慢慢的也就弄清楚了这些东西，应该不到两个月的时间吧，我就已经可以独立开发制作平台功能。我心里一直非常感谢军哥和产品老大，给了我这个机会学习和实践，让我现在能顾有底气的说我是一名前端开发者。
2. [70度微店铺](http://shop.70c.com/ecindex/Index) *场景预览*
3. [70度微店铺商家管理移动端](http://mseller.70c.com/)
4. [疯传商城](http://shop.fengchuan.me/) *仅参与部分*
5. [全员纷享移动端](http://user.qyshare.cn/Content/home/)

今年我们也有了自己的前端技术周刊 － [学前班](http://f2e-journey.github.io/xueqianban/#)，我们每周都会把自己所见觉得好的内容分享出来，截止今天，已经有 40 期内容。

### 生活
去年年会 (2016.1.22) 那天意外脱单，开始了两个人加一只猫 (英短) 的小日子。她是个典型的吃货，现在已发展成每周周末必去商场吃大餐，而且很少吃重复的，不禁感概不仅中国文化博大精深，连美食也一样，今年一年吃过的花样比之前二十年还要多。结果体重增长是肯定的，脸上也冒了一些坨，肚子也还是没有还原当年的腹肌，幸好今年还有坚持运动，不然后果简直不堪设想，我真的好怀恋当年的腹肌 ...

陪伴我战斗近 5 年的笔记本终于退休，在 MacBook Pro 2016 款出来之后购置了一台 15 寸的 2015 款。16 款概念太先进，Touch Bar 对设计、音乐、视频行业比较友好，写代码貌似用处不大，TypeC 接口太前卫，让市场接受并普及估计还需要两年时间，在这之前如需使用也还需付出高额的配件费用，其他都不做评价。这就是我为什么选择 15 款，当然，还有价格原因，15 寸标配 18k＋，高配 21k＋，让我不得不承认我有点穷 ...

《浪潮之巅》、《追风筝的人》、《从你的全世界路过》、《极简欧洲史》、《冰与火之歌》、《解忧杂货店》、《嫌疑人x的献身》、《岛上书店》、《穷爸爸富爸爸》
以上是我几年看过的书，可能有遗漏，今年貌似没有看任何一本技术方面的书籍，可能是因为买了 kindle 之后能看的书太多，技术相关的书籍就延迟推后啦。不过对现在的我而言，技术相关的书籍需求貌似不大，所有盲点都直接科学上网寻找答案，现在一般都是遇到问题解决问题，学习新的东西也不需要书籍，直接看官网教程就 OK。其实用来看书的时间也没有多少，工作睡觉就占据了三分之二的时间，剩下三分之一的时间也要要陪女朋友和家人、充电学习、运动、写博客 (今年下半年开始)、偶尔加班等等，看书的时间大多数都是晚上睡觉之前。
推荐阮一峰老师今年的新作[《未来世界的幸存者》](https://ruanyf.github.io/survivor/)，这个世界正在朝着某个方向慢慢改变。

总体来说，生活没有大变化，正在一步一步往前走。

### 前端
今年下半年在前端的学习上有了一些思想上的转变，不再盲目追新，除了随用随学之外，更在注重基础。毕竟我属于半路出家，基础不扎实，技术栈也落后了好几年，虽然一直在填补，但到了某个层度之后，举步维艰。很多技术的思想、底层原理、算法之类的知识是我一直欠缺的，这是一段艰难的路，需要一步一个脚印坚持走下去。

年中旬觉得是时候搭建一个属于自己的博客，积累、整理和记录自己的成长，就用 [Hexo](https://hexo.io/zh-cn/index.html) 结合 Github 快速搭建了一个博客，但心里总有一个疙瘩，作为一枚前端，搭建一个博客居然还需要使用这种一键式工具，毫无自己创意和发挥，实在无法接受，就想要自己纯手工搭建。Vue.js 是我上半年接触到的框架，当时觉着它跟 AngularJS 很类似，也有双向数据绑定、组件什么的，对它的理解不深。后来它越来越火，发展到与 React 一争高低，才让我又去重新认识它一遍，当时还是 1.x 到版本。按照官网给的介绍，使用 Vue 的脚手架工具 vue-cli 快速完成了 demo，我记得当时还不太明白单文件模块到底怎么玩，从网上查了好多资料才理解，觉得这东西真牛 13，我要用它来搭建博客。因为 vue.js 的教程内使用的都是 ES6 语法，自己也觉着是时候来学习 ES6 的知识啦，就两者一起啃了下来。前前后后经过一个月左右的时间，利用下班时间完成了 [vue-blog](https://github.com/Monine/vue-blog) 项目，又写了一篇文章 [我是如何纯手工打造这款 Vue Blog 的](https://monine.github.io/#/article/7) 记录下来，主要是设计这块花了许多心思，毕竟当年哥也是学设计出身，强迫症和洁癖让我对细节十分纠结 。博客搭建好没多久，vue.js v2 来袭，当时工作太忙，没太关注，过了两个月，也就是 12 月中旬 (上上个星期)，才开始着手升级迁移。由于项目本身不复杂，没花多长时间就完成了升级迁移，然后也写了篇文章 [Blog (Vue.js) v2.0 升级 (迁移) 指南](https://monine.github.io/#/article/11) 记录下来。

node.js 今年也有涉猎，大致了解了一遍，由于没有什么可行的项目实践，时间一长，也忘的七七八八，好在已经过了一遍，以后要重新捡起来也容易。

今年在前端领域也算有了一个新的突破、提升，明年的目标是继续扎实基础、使用 node.js 做一个小项目、玩转微信小程序，给 Blog 继续升级，使用 vue.js 开发工具和插件。

嗯 ... 就酱，2016 拜拜！

你好，2017 ...

**Comment by YinPen** [comment]
太优秀， 生活和工作过得这么惬意， 舒心， 令人敬佩👍
