### ISSUE TITLE
动态数据绑定的理解 - Vue.js 早期源码

### ISSUE THREAD

**Issue by Monine** [Monine/monine.github.io#16]
IFE 百度前端技术学院 2017 年已经开课，今年跟以往不同，内容非常丰富，可以自己选择感兴趣的内容学习并完成作业。不仅有最基础的课程：小薇学院（HTML、CSS）、斌斌学院（JavaCcript）、耀耀学院（综合实战），还有学院公开课：商业平台学院、ECharts & WebVR学院、百度糯米前端技术学院，百度今年是真的花了心思的！虽然不太认同百度在国内的一些行为，但是百度的前端团队还是非常值得称赞的。

![](https://picabstract-preview-ftn.weiyun.com:8443/ftn_pic_abs_v2/77c704ff742d736200e4b9751537c171a1416979a02aaf60080ec84b71658272d092c745c82dd01630b1895427a5d18d?pictype=scale&from=30013&version=2.0.0.2&uin=287531381&fname=vue-response-principle.jpg&size=1024*1024)

在百度糯米前端技术学院的课程内有关于 Vue.js 的动态数据绑定由浅入深的课程，总共 5 课，我花了一个星期的个人时间算是简单的完成了任务。对我而言可谓是非常的艰难，尤其最后一课，完成的十分艰难，动态数据绑定的概念十分难理解，我最后是照着课程提供的参考找到实现的源码，用 ES5 重新写了一遍，反复研究很多次才算是有了基本的理解吧。

动态数据绑定的实现我把它分为以下 5 个点：
- Observer（观察）
  Observer 实现数据观察、事件的添加和触发，当数据发生变化时触发对应的事件，包括更新 DOM 和 自定义事件。
- Compile（编译）
  Compile 编译 `el`，找到 `el` 内所有绑定了数据的 node，对其绑定 Directive。
- Directive（指令）
  Directive 实现更新 DOM，每个 directive 都包含当前 node 对应的 Watcher，并保存在 Vue 的`_directives` 数组内。
- Watcher（订阅）
  Watcher 执行更新 DOM，Vue 的 `_rootBinding` 对象内对应 `data` 内的属性会拥有当前 watcher。
- Binding（绑定）
  Binding 订阅绑定，Vue 的 `_rootBinding` 对象内的属性是按照 `el` DOM 内用到的数据层层深入排列下去的，包含一个 `_sub` 数组，里面存放的就是当前属性发生变化之后执行的所有 watcher。

这么粗略的描述是肯定无法理解的，反正我到现在都还处于挺懵的状态，这里面的东西太复杂啦，就算知道作者在写什么，也很难理解其中的细节缘由，而且这些都还只是最基本的实现中的最基本理解。不过通过此次源码阅读分析倒是又增长了见识，开阔了眼界，平时工作中业务需要实现的代码跟这个基本不挂钩，也就是说基本没有这样写过代码，现在能够基本理解并实现动态数据绑定，内心还是非常激动的。下面我就来说说具体实现：

示例代码：
```
<div id="app">
  <p>姓名：{{ user.name }}</p>
  <p>年龄：{{ user.age }}</p>
  <p>身高：{{ height }}</p>
</div>Ï

<script>
var app = new Vue({
  el: '#app',
  data: {
    user: {
      name: 'monine',
      age: 25
    },
    height: 178
  }
})
</script>
```

引用 [@youngwind ](https://github.com/youngwind)的重要图片一张：

![](https://raw.githubusercontent.com/youngwind/blog/master/image/87/finish.png)

### Observer

数据初始化，给 `data` 对象及其所有子对象（示例代码子对象只有 `user`）创建 $observer，在所有子对象的 $observer 内添加 `parent` 属性，包含父级的属性 `key` 和观察者 `ob`。使用 `Object.defineProperty` 重新定义每一个属性（`user` `name` `age` `height`），在属性的 set 方法内添加 notify 通知，用于更新 DOM 和触发自定义事件，并且会通过 `parent` 属性层层往上发出 notify，因为监听的是 `data` 的 $observer 对象，是一个深层次监听，也就是说 `data` 的任何子属性发生改变都会 notify 到 `data` 的 $observer。我记得以前使用 AngularJS 1.x 的 $watch 方法的第三个参数如果设置为 `true`，那也是这种深层次监听。

### Compile

编译 DOM，这应该是最麻烦的一部操作，不过我这里的实现非常简陋，只对 `{{ user.name }}` 这种双大括号类型进行处理，遇到这种 node 就绑定 Directive。其它就引用 @youngwind 的描述：
> 在遍历DOM模板的过程中，当遍历到文本节点："{{name}}"的时候，会先将其中的表达式"name"匹配出来，然后新建一个空的textNode，也就是上面的this.el，插入到这个文本节点的前面，最后remove掉这个文本节点。这样，就实现了用一个程序生成的textNode代替原来的textNode，从而实现每个textNode都跟它的表达式一一对应起来。

### Directive

directive 会包含当前节点名称、元素、vm、表达式、赋值属性、watcher 和更新方法，以 `{{ user.name }}` 为例，节点名称为 “text”，元素就是上一步编译之后重新创建用来替换原来节点的 el，vm 是当前 Vue，表达式是 `user.name`，赋值属性是 `nodeValue`，`new Watcher` 新增  watcher（这就是 Directive 和 Watcher 产生联系的地方），更新方法就是一系列的指令对应的方法，这里的话就只有 ”text“ 的 `update` 方法。 

### Watcher

引用 @youngwind 的描述：
> Watcher是一个观察容器，它既可以装载Directive，这时候cb是更新DOM的函数，从而实现数据变动的时候更新DOM；也可以装载$watch，这时候cb是自定义的回调函数，从而实现数据变动的时候执行自定义回调函数。

Watcher 其实就只做一件事情，装载指令，要么用来更新 DOM 的 Directive，要么就是自定义的回调函数。最后被存放到 `_rootBinding` 内对应属性的 `_subs` 数组。一旦页面中被绑定的数据发生变化，对应的  `_subs` 数组内的 watcher 会被循环执行，从而实现动态数据绑定。

### Binding

 往 Vue 的 `_rootBinding` 内对应的属性上添加订阅，也就是 watcher。当 `_rootBinding` 对应的属性没有 Binding 对象的时候就会 `new Binding()` 生成一个，有的话则会直接返回 Binding，另外就是往对应属性的 `_subs` 内添加 watcher。

详细请看：
- [vue早期源码学习系列之四：如何实现动态数据绑定 ](https://github.com/youngwind/blog/issues/87)
- [我的作业](https://github.com/Monine/study/blob/master/IFE-2017/rice/dynamic-data-binding-5.html)

写出此文记录的同时加深对动态数据绑定的理解，虽然感觉就算明白了目前也并不会在工作上有什么用处，但是相信对以后的前端路肯定是会有帮助的。
面对这种复杂的设计和架构，如何尽快让自己理解呢？首先肯定是要利用 Google 找几篇大神们已经产出的文章瞧瞧，阅读过后可能还是感觉很迷糊，不明白到底是怎么玩的，但是至少已经明白其中涉及到的一些概念和大概的轮廓，然后接下来就要靠自己的能力去破解其中的奥秘啦。在阅读这种比较复杂不好理解的源码的时候，我的方式就是按照源码的执行顺序，自己照着源码抄袭写一遍（如果是 ES6 的就写成 ES5 的），每一步都尽可能的联系上下文，写完之后再回过头去多执行理解几遍，就会有基本的理解。然后写下一篇记录性的文章，尽可能的把自己的理解用文字描述出来，越是复杂的东西其中的细节就会越多，写文章的同时又会对源码进行一次联系上下文对解析，很有可能又会有新大陆被发现。

**Comment by sixgod666** [comment]
非常感谢 ES6好多语法看的我一脸懵逼 而且少峰大哥的代码分散在无数个文件里 看了好几天头大了不少
