### ISSUE TITLE
关于近期离职

### ISSUE THREAD

**Issue by Monine** [Monine/monine.github.io#18]
2017 年才工作一个月的时间，突然就被告知公司正在研发项目被砍，暂时没有项目可做，研发的人员被遣散，只留下前、后端负责人。

![](https://picabstract-preview-ftn.weiyun.com:8443/ftn_pic_abs_v2/41a9ea0b24748de3df3321fa2c642c8abe4e5cdaa45c969aa3aea3317d7500c718214ae247b04d6e2711502413f99a35?pictype=scale&from=30013&version=2.0.0.2&uin=287531381&fname=keyboard-quit.jpg&size=1024*1024)

### 3 月 3 号星期五 阴天

因身体不适在家休息，部门前端小妹纸发消息跟我说项目不做了，大家都被产品老大叫去谈话，意思是都要被辞退。当时我还有点低烧，正在家躺着休息，看到消息也没有太在意，因为去年下半年就已经有一轮裁员风波，另外一个项目的研发人员基本全走，但是至少会提前有消息告诉大家，然而这次貌似有些意想不到的突然，明明昨天还好好的，正在高高兴兴的写 Vue 的代码。

### 3 月 6 号星期一 晴天

我到公司没多久，果不其然产品老大也把我叫到会议室谈话，说公司发现现在做的项目有很大的法律风险，立即给叫停啦，然后公司目前还没找到合适的新项目，所以暂时不需要这么多研发人员啦。看得出来产品老大也是很为难，毕竟我们都是这家创业公司的老员工啦，好不容易这么一帮兄弟聚在一起，现在都要离开，他心里也是非常不舍。然后跟我说他的想法是把我推荐给兄弟公司微时代，能保证待遇跟这边一样，等智云这边找到新的产品重新发展起来，再把我从微时代这边要回来，问我愿不愿意。

让我去微时代这个我确实是没想到的，一时之间我也想不清楚我应该怎么回应，就跟产品老大说让我想想，我明天给你回复，然后上午就在公司打了个酱油，下午又调休回去休息啦。下午在家躺着不自觉又想了很多，从毕业后到现在，我经历了很多事情，意识到身体健康的重要性，明白了身边最重要的人是哪些，也在自己的努力下找到了自己的目标，重新选择了方向。

我一直认为，每件事情都有它的两面性，如果这次裁员对我而言是它不好的一面，那这件事情的好的一面是什么呢？我认为是我又有了新的选择机会，如果不是因为这次裁员，我应该是会继续待在这家创业公司继续发展，因为要学的还有很多，军哥这边在前端方面还能够提供给我很多的指导，产品老大也很看好我，我也能够带领前端的新人学习，等等...而现在，面对这次机会，我想我是需要好好把握住的，我的想法是希望能够去一线的互联网公司发展！

### 3 月 7 号星期二 晴天

一大早来到公司，等产品老大来了就把他叫到会议室告诉他我的想法，微时代那边我是不打算去啦，这次裁员对我而言也算是次机会，趁着还年轻，我想去一线城市发展。后面还谈了什么我也不太记得啦，总之今天看军哥怎么安排，然后军哥是安排了我一些微时代那边的工作，完成之后就把工作交接下就可以办离职手续啦。

上午很突然，被微时代那边的研发老大旺哥（去年下半年智云被砍项目的后端老大）叫到会议室聊了会，跟我说了下微时代那边现在的情况，说希望我能够去微时代做前端，待遇方面是能够保证的，然后前端可以让我当个小 leader。真是风水轮流转，2015 年我刚加入智云那会正是智云如日中天的时候，微时代还没有研发人员，而现在智云已经日落西山，微时代却朝气蓬勃在加强研发人员实力，有些戏剧化。我对旺哥表示了感谢，感谢他对我的赏识和给我的机会，但我还是跟旺哥说明了我的想去一线城市发展的想法，旺哥听了之后也对我的想法也表示支持，说如果是去一线城市发展他就不挽留啦，年轻人出去闯荡是有好处的，如果想继续待在长沙发展欢迎来微时代。嗯...谢谢旺哥。

下午办完所有离职手续跟产品老大、军哥、果哥（后端老大）道别，产品老大这时候跟我说他个人是非常希望我去一线城市发展的，那边更适合我...然后问我下周还在不在长沙，智云研发的兄弟一起聚聚吃个饭，我说好，没问题，挥手道别，就这样，我离开了智云。

### 3 月 15 号星期三 小雨

晚上跟前智云的小伙伴们在一起聚餐，聊了很多，大家的最新去向，吐槽互联网资本寒冬，长沙的互联网公司发展动向，VR、AI 等最新技术，连外星人、多维空间也扯出来了。此次聚过之后，不知道要过多久才会有下一次聚在一起的时候，心里还是有些小伤感的，毕竟这一年多每个工作日都是跟这帮小伙伴在一起奋斗，跟他们在一起的时间比父母和最好的朋友都长，一起做了那么多有意思的事，吹了那么多牛，天南海北聊了个遍。感谢智云把我们聚在了一起，让我认识了这么一帮有趣又无趣小伙伴，我的前端导师军哥，我打心底里的感激，没有他的指导我不会成长的这么快，与其说是对公司的感情，不如说是对公司里这些人的感情吧，希望这些小伙伴们都能越来越好。

### 3 月 16 号星期四 阴天

说下自己为什么会转行做前端吧...

其实当初选择前端这条路是巧合也是必然，因为毕业后的一年多的时间也算是经历了我目前为止人生的最低谷，14 年下半年那时起就开始对自己的人生进行反思，我希望成为一个什么样的人？我想要什么样的人生？我适合或不适合做哪些事情？乘着我还年轻，还有得选择，还能够选择，赶紧把自己人生的方向调整调整，找到自己真正喜欢且能够保证生存的行业。后来我选择前端的理由是这样的，因为现在是互联网时代，身处在这个时代如果不加入其中做点什么会后悔终身，so...选择互联网行业，那互联网行业这么大，我能够做什么呢？因为我大学是学室内设计的，就有想过做 UI 设计、交互设计之类的，但是我也知道自己的在设计方面的造诣实在不咋地，所以还是算了吧。后来刷知乎的时候发现有个外国妹纸用[180天做了180个网页](http://jenniferdewalt.com/index.html)，然后怎样怎样，这个时候我才真正发现前端这个行业的存在，才开始了解这个行业，那时候觉得前端跟室内设计很相似，室内设计是对房子的三维空间进行布局、装饰，而前端则是对网页进行布局、装饰并且实现，经过一些心路历程，决定就是前端啦，然后就模仿那位外国妹纸每天利用下班时间做出一个页面。之后的半年时间，基本上每天晚上回家就是学习前端知识，直到感觉自己已经无法依靠个人修行继续提升，就来到长沙麓谷求职前端岗位，最终来到智云。

**Comment by HumiH** [comment]
博主居然是从设计转前端的,佩服.一直在关注你的博客,祝你能找到好工作.

**Comment by Monine** [comment]
@HumiH 
感谢关注，谢谢祝福...
现在也正为奔向一线互联网公司而努力中，希望能够取得自己满意的结果。
