### ISSUE TITLE
Vue SPA 工程三大优化

### ISSUE THREAD

**Issue by Monine** [Monine/monine.github.io#20]
1. 动态加载路由（会先说说权限配置）
2. 异步加载模块
3. 打包（build）之后的依赖（vendor.js）文件太大

![buile-spa-vue](https://picabstract-preview-ftn.weiyun.com:8443/ftn_pic_abs_v2/efe12fb7fb7f966056fa56cd6345a1e0ab81cc7ecbc3f2b3bab32378c3bdea4593d3c0d586ff9d9d093f7c12032a0db2?pictype=scale&from=30013&version=2.0.0.2&uin=287531381&fname=buile-spa-vue.jpg&size=1024*1024)

### 1. 动态加载路由

> 根据 API 返回的角色类型添加相对应的权限路由

这里先说下为什么需要动态加载路由？这里就需要先提及权限控制这一需求。

做过管理后台的同学应该都知道权限这一需求，不同的角色拥有不同的权限，权限对应的就是拥有的能力，在路由层面，就是控制角色所拥有的页面。权限完全可以由前端掌控，这样也可以避免开发过程中对后端的依赖，避免不少麻烦事，这里只是说前端能够做到权限控制，至于项目中还是要按实际需求来。

前端实现权限控制的方式非常简单，说下我的实现方式，前端定义页面路由时在 `meta` 字段添加可访问角色列表。

``` javascript
// 定义路由
const router = new VueRouter({
  routes: [
    {
      path: '/foo',
      component: Foo,
      children: [
        {
          path: 'bar',
          component: Bar,
          // a meta field
          meta: {
            roleList: ['monine'] // 允许角色 monine 访问当前路由
          }
        }
      ]
    }
  ]
})
```

*只有当角色类型为 `monine` 时才能访问 `/foo/bar` 路由页面*

后端在登陆的 API 内返回用户的角色类型，前端在 `vue-router` [导航钩子](https://router.vuejs.org/zh-cn/advanced/navigation-guards.html) 的全局钩子 `beforeEach` 函数内对 `to` 路由信息对象进行角色类型判断，如果目标页面路由有权限要求，并且 `to.meta.roleList` 内有当前用户的角色类型，那么直接 `next()` 进入目标页面，如果没有当前用户的角色类型，那就做对应的无权限操作，比如跳转到 404 页面或是无权限提示页面。

``` javascript
// 导航钩子
router.beforeEach((to, from, next) => {
  if (to.meta.roleList) { // 如有目标页面有权限要求
    if (to.meta.roleList.indexOf(userRole) > -1) {
      next()
    } else {
      // 当前路由的角色列表内没有当前用户的角色
      // 则跳转到 404 页面或是无权限提示页面
      // 并记录原本目标页面地址到 URL 查询参数
      next({
        path: '/404',
        query: { redirect: to.fullPath }
      })
    }
  } else {
    next()
  }
})
```

*在每一次路由跳转时进行目标页面权限判定，如果有权限要求并且路由权限列表找不到当前用户的角色，则进入 404 页面 `/404?redirect=%2FfullPath`*

以上，用前端的方式实现了权限控制，那换个角度思考，与其在每次路由跳转时做权限判断，在初始化加载拿到用户角色类型之后，针对角色类型生成对应的路由表不就行了吗？也就是接下来要说的**动态加载路由**。

OK，进入正题...

动态加载路由的想法是没有问题的，可落实到实现就是个麻烦事，Google 貌似也找不到什么详细介绍的文章或案例（有可能是我搜索的方式有问题...）。后来我也是无意之中才发现这块新大陆，那就是 vur-router 的一个非常不起眼的方法 `router.addRoutes(routes)`，要不是官网把这个方法的介绍说明排版错误，我估计都发现不了它...

*官网唯一介绍*
> router.addRoutes(routes)
> 2.2.0+
> 动态添加更多的路由规则。参数必须是一个符合 routes 选项要求的数组。

除了以上引用，官网就真的再也没有任何地方提到过这个方法，反正我是没有看到...

接下来就说说**动态加载路由的具体实现方式：**

首先路由的实现需要分为两块，一个是基础（无权限）路由列表，一个是需要权限的路由列表，并且还需要注意一点，`router.addRoutes(routes)` 这个方法只能往一级路由表添加路由，不能单独添加嵌套路由内的路由，不知道怎么说清楚，看下面代码示例应该能明白。

``` javascript
const router = new VueRouter({
  routes: [
    {
      path: '/foo',
      component: Foo,
      children: []
    }
  ]
})
// 需要动态添加嵌套路由 /foo/bar
// 这时无法动态添加 /foo 路由下的 children 路由列表
// 只能往一级路由表单个添加
router.addRoutes([{ path: '/foo/bar', component: Bar}])
```

在实际项目中，肯定很多很多路由配置，而且嵌套路由也必不可少，这就增加了动态加载路由的复杂度，不过没关系，有挑战才会有意思、有成就感，OK，继续往下说。

基础（无权限）路由列表就是一些首页、404页面、介绍说明页面等等，写死的配置，在初始化路由时就绑定。

权限路由列表需要根据当前用户的角色类型动态生成，然后使用 `router.addRoutes(routes)` 方法动态添加。代码的实现稍微有点复杂，因为权限路由可能会有嵌套路由，所以需要使用递归插入来实现，具体请看以下代码：

``` javascript
*** router.js ***
export const dynamicRouteList = [
  {
    path: '/async',
    component: Async,
    children: [
      {
        path: 'first',
        component: Async,
        children: [
          {
            path: 'xxx',
            component: Async,
            meta: {
              roleList: ['monine']
            }
          },
          {
            path: 'yyy',
            component: Async,
            meta: {
              // 未设置 roleList 字段表示任何角色都能够访问此路由
            }
          }
        ]
      },
      {
        path: 'second', // 这个路由最终不会被添加，因为所有子路由都不能被角色 monine 访问
        component: Async,
        meta: {
          // 错误！！！父级不应该有权限字段
          // roleList: ['monine']
        },
        children: [
          {
            path: 'xxx',
            component: Async,
            meta: {
              roleList: ['xxx']
            }
          },
          {
            path: 'yyy',
            component: Async,
            meta: {
              roleList: ['yyy']
            }
          }
        ]
      }
    ]
  }
]
```

``` javascript
*** main.js ***
// 模拟 API 返回
setTimeout(() => {
  const role = 'monine' // 假设角色为 monine
  const permissionRouteList = generatePermissionRouteList(dynamicRouteList, role)
  if (permissionRouteList.length) router.addRoutes(permissionRouteList)
}, 1000)
```

``` javascript
*** app.js ***
function addPermissionRouteList (dynamicRouteList, permissionRouteList, role) {
  dynamicRouteList.forEach(route => {
    if (route.children && route.children.length) {
      // 进入这里表示当前路由有子路由
      // 先插入当前路由数据，但是要把 children 字段设置为空数组
      // 因为还要对当前路由的子路由逐一进行权限判断
      // 符合权限要求的才被插入 children 字段
      permissionRouteList.unshift(Object.assign({}, route, { children: [] }))
      // 递归执行 addPermissionRouteList 方法
      // 参数为 当前路由的子路由 children、上一步插入的路由数据的 children、角色
      addPermissionRouteList(route.children, permissionRouteList[0].children, role)
      // 如果上一步没有往 permissionRouteList[0].children 插入路由数据
      // 则删除第一步插入的路由数据
      if (!permissionRouteList[0].children.length) permissionRouteList.shift()
    } else {
      // 进入这里表示当前路由没有子路由
      // 也就是说已经到达最终页面路由
      if (route.meta && route.meta.roleList) {
        // 进入这里表示当前路由有权限要求
        // 并且当前路由权限列表有当前角色类型
        // 则往 permissionRouteList （父级路由 children 字段）插入当前路由数据
        if (route.meta.roleList.indexOf(role) > -1) permissionRouteList.unshift(route)
      } else {
        // 进入这里表示当前路由没有权限要求
        // 直接往 permissionRouteList （父级路由 children 字段）插入当前路由数据
        permissionRouteList.unshift(route)
      }
    }
  })
}

export function generatePermissionRouteList (dynamicRouteList, role) {
  const permissionRouteList = []
  // 添加权限路由
  // 传入的参数为 动态路由列表、权限路由列表、角色
  addPermissionRouteList(dynamicRouteList, permissionRouteList, role)
  return permissionRouteList
}
```

*上面的实现代码是可以直接拿来使用的，如果有什么问题欢迎交流。*

两个需要注意的点：
1. 如果最终路由没有设置权限字段则表示任何角色都能够访问
2. 权限字段应该设置在最终路由页面层级，而不应该出现在任意父级层级，如果某个路由的所有子路由针对某个角色全都没有权限访问，那么这个路由也不应该被添加。

至此，动态加载路由的优化方案就实现完成啦，依据以上两点，根据项目实际需求再做一些细节调整，融入项目中去应该是没什么问题的。

### 2. 异步加载模块

老问题，为什么需要异步夹杂模块？相信做过中大型项目的前端同学能够明白这一痛点，随着项目代码的增多，生产环境打包出来的 app.js 文件随之增大，严重拖慢页面初始加载速度，这个时候就需要对一些不需要第一时间加载的模块（页面）执行懒加载方案，说通白点，就是用户打开一个页面就下载一个页面的内容。还有一点，就算我们实现了动态加载路由，但是所有动态路由的组件都还是被打包在 app.js 文件内，也就是说在用户打开页面时，一些当前用户所属角色类型没有权限访问的页面组件代码也被下载下来（在 app.js 文件内），那也就是说 app.js 文件内很多代码的是当前角色用户永远不会执行的！以上两点，足以说明异步加载模块的必要性。

官方说明：
- [Vue.js 教程：异步组件](https://cn.vuejs.org/v2/guide/components.html#异步组件)
- [vue-router.js：路由懒加载](https://router.vuejs.org/zh-cn/advanced/lazy-loading.html)

实现需要使用到 [webpack 代码分离 - 异步](https://doc.webpack-china.org//guides/code-splitting-async/#require-ensure-)，具体怎么做都已经说的非常清楚，我也无需多言，有不明白的欢迎交流。

### 3. 打包（build）之后的依赖（vendor.js）文件太大

这也是前端性能的一大痛点，第三方依赖太多导致生产环境打包后的 vendor.js 文件太大，该如何来优化呢？

前端同学都知道比较流行（出名）的第三方依赖（插件/库）在公共 CDN 上都是存在的，所以我们可以将一些依赖通过 script 标签的形式引入，但是这样会面临一个问题，模块化开发在需要依赖插件的地方如何引入呢？依赖资源从 CDN 上加载，本地是没有的，所以使用 `import` 或是 `require` 引入依赖是找不到依赖资源的。

那我们现在要解决的问题就是在使用 script 标签加载依赖资源的情况下，如何才能通过 `import` 或 `require` 引入这些依赖资源？

webpack 有一个叫 [Externals（外部扩展）](https://doc.webpack-china.org/configuration/externals/) 的配置项，它的作用是「从输出的 bundle 中排除依赖」，官例是从 bundle 中排除 jQuery，通过 script 标签从 CDN 引入，然后依然可以使用 `import` 语法引入 jQuery。

``` html
*** index.html ***
...
<script src="https://code.jquery.com/jquery-3.1.0.js" integrity="sha256-slogkvB1K3VOkzAI8QITxV3VzpOnkeNVsKvtkYLMjfk=" crossorigin="anonymous"></script>
...
```

``` js
*** webpack.config.js ***
externals: { 
  jquery: 'jQuery' 
}
```

在项目代码中不用改动任何内容还是依然可以正常运行，如下：

``` javascript
import $ from 'jquery';

$('.my-element').animate(...);
```

要完全理解 Externals 这个配置项还是比较吃力的，需要对模块化开发各种代码执行环境有所了解，这里我只说明在浏览器环境中，其实就是把 `jQuery` 挂载到 `window` 上，然后导出为一个模块文件，提供给其他文件引用加载。需要注意一点，引用依赖的时候资源名称是配置项 `externals` 内的 key，也就是上面的 `jquery`，而非 `jQuery`。

想要详细弄清楚 Externals 配置项可以看看以下两篇文章：

- [webpack externals详解](http://www.tangshuang.net/3343.html)
- [webpack中library和libraryTarget与externals的使用](https://github.com/zhengweikeng/blog/issues/10)

**Comment by MillerRen** [comment]
页面刷新的时候，路由表还没加载怎么办呢？

**Comment by Monine** [comment]
@MillerRen 
不太明白为什么会出现你说的这种情况...

路由表只是一份配置内容，Vue 实例化之前根据用户角色和路由表动态生成注入 Vue 实例的路由配置，然后 vue-router 会根据 URL hash 加载对应的异步组件渲染页面内容。

如果上面的解释不是你所问的，还请你详细描述你的疑问。

**Comment by MillerRen** [comment]
如果是类似/a/b/c/d/e/f等比较深的路径的时候，路由表还没有加载，页面不会404么（路由到404）？

**Comment by Monine** [comment]
@MillerRen 
这根路由表的深浅无关，动态路由表总是会在页面组件内容渲染之前就根据角色确定，而静态路由表则就类似于一份配置文件，包含所有路由。
动态路由表实际就是根据角色从静态路由表取当前角色能够访问的路由信息，然后注入到 Vue 实例，如果动态路由表内没有当前访问路径肯定就访问不了，如你所说，就是进入 404 页面。

我还有哪里没说清楚吗？欢迎交流。

**Comment by MillerRen** [comment]
如果页面刷新了就404，体验肯定不好，我正在找类似的解决办法

**Comment by Monine** [comment]
@MillerRen 

可是当前用户没有权限进入此页面呀...

你当然也可以做个 401 页面，页面内容就是提示当前用户没有权限访问此页面。
在生成动态路由表的时候照样插入无权限当前路由，只是配置为重定向到 401 页面，这样应该不影响体验吧。

**Comment by humorHan** [comment]
异步组件a中再异步加载b会怎样，还是打出一个包a还是两个包a和b
