### ISSUE TITLE
ScrollBar 的归属 - 谁拥有滚动条？

### ISSUE THREAD

**Issue by Monine** [Monine/monine.github.io#9]
众所周知，任何块级元素只要设置 `overflow` 属性可以拥有滚动条，那还有一种情况，页面没有设置 'overflow' 属性， 但是页面内容超出浏览器窗口大小，滚动条会自动出现，它从哪里来呢？

![](https://picabstract-preview-ftn.weiyun.com:8443/ftn_pic_abs_v2/a18ecce7e45efcd6cc42e147d05d046a31c17020ac2b2e65364346a2f341871fa2fd34748663f95b5690a63649b853b5?pictype=scale&from=30013&version=2.0.0.2&uin=287531381&fname=whose-scrollbar.jpg&size=1024*1024)

### 关于滚动条

在上一篇文章 [梳理 Javascript 各种宽高属性](https://monine.github.io/#!/article/8) 研究这些宽高属性的时候，发现一直有个叫做滚动条的东西神出鬼没特碍事，时刻得考虑到它存在时所带来的影响。突然我脑海中浮现一个很不明显的问题，在一般情况下，页面内容多到一定层度，滚动条就会自己出现，咱是不是根本没有呼叫它？它咋就这么厚脸皮的出现啦了？你说它爱出现就让它出现吧，尼玛它还要作死的来影响咱页面的大小。假设页面在没有滚动条时的宽度是 1000px，那在有滚动条时，页面的宽度瞬间减少一个滚动条这位大爷的宽度 (17px)，只有 983px 啦。而且页面在有滚动条和无滚动条变换时还会导致页面 “颤动”，就像是这人抖了以下的感觉，相信也有不少 前端er 遇到过这样的问题，无论是不是强迫症患者都会感觉特难受。其实我的 Blog 页面也遇到了这问题，解决办法可以打开开发者工具看看 `body` 元素的样式就一目了然啦。

BB 了这么多，其实我想说的那个很不明显、不容易被察觉到的问题是：

> 这个滚动条是属于谁的？

想想...

细想一下...

容朕认真思考...

相信不少 前端er 的第一反应是 `body` 元素，好吧，我承认之前我的第一反应就是 `body` 元素。因为以前有遇到过需要隐藏页面滚动条的情况，实现就是直接在 `body` 元素上添加 css `overflow: hidden`。神马？听着哪里不对劲？怎么说得好像不是 `body` 元素似的...

嗯... 没错，确实不是 `body` 元素，正确答案是 `document`。

### wu ai why？

首先，我利用上篇文章研究的宽高属性进行了一些思考和实践，`body` 是一个 element，那么它拥有上篇文章介绍的 element 所有可使用宽高属性，以 `width` 为例，咱可以使用的就是：

- `document.body.clientWidth`
- `document.body.offsetWidth`
- `document.body.scrollWidth`

OK，接下来就想想如何依靠这三个属性来判断 `body` 元素是否有滚动条。如果有仔细看上篇文章内容并且有思考过的小伙伴一定能发现：

> `offsetWidth = clientWidth + scrollBar + border`

没错，利用 `clientWidth` 和 `offsetWidth` 可以很容易判断出任何元素是否有滚动条，只要满足以下这个公式：

> `offsetWidth - border > clientWidth`

很显然，当 `body` 没有 `border` 的情况下，只要 `document.body.offsetWidth > document.body.clientWidth` 就可以做出判断，滚动条是属于 `body` 元素的。然而，就像人生的道路绝对不适一帆风顺的一样，经过测试发现 `document.body.offsetWidth === document.body.clientWidth`。

So... 结论就是：**页面的滚动条并不是属于 `body` 元素的**，但是！给 `body` 元素赋予 `overflow` 属性是可以控制页面的滚动条是否显示的。现在已经确定不是 `body` 元素，那难道是 `html` 元素？是不是呢？咱测试一下就一清二楚啦，结果发现：

*跟 `body` 元素的结果一模一样！OMG...*

也不是 `html` 元素的，那继续往上层找就是 `document` 和 `window` 对象啦，这它两好像并没有办法使用宽高属性去判断是否拥有滚动条呀，这可如何是好？呃... 一休哥附体，打坐 =)+(=

滚动条...

滚动...

scroll...

想到了！聪明如我，经过几分钟冥想，想到 `scroll` 事件，事件触发的回调函数会默认有个 `event` 参数，这个参数包含一大堆关于事件的属性，就在这些属性中，就有我们 “谁拥有滚动条” 这个问题的答案。

**谁触发的 `scroll` 事件，谁就是滚动条的拥有者。**

没错，`event.target` 就是滚动条的拥有者，想知道它幕后真面目的 前端er 同学赶紧打开开发者工具动手行动起来吧！

*其实判断 `body`、`html` 是否拥有滚动条最简便的方式就是打开开发者工具，这鼠标移到这两个元素标签上，瞧瞧看页面被蓝色遮罩的区域内是否包含页面滚动条就清楚了。*

**Comment by lorainwings** [comment]
mark  插眼
